export const environment = {
  production: false,
  jwtSecretKey: 'YOUR_DEVELOPMENT_JWT_SECRET_KEY',
  apiUrl: 'YOUR_DEVELOPMENT_API_URL',
  firebaseApiKey: "YOUR_DEVELOPMENT_FIREBASE_API_KEY",
  firebaseAuthDomain: "YOUR_DEVELOPMENT_FIREBASE_AUTH_DOMAIN",
  firebaseDatabaseURL: "YOUR_DEVELOPMENT_FIREBASE_DATABASE_URL",
  firebaseProjectId: "YOUR_DEVELOPMENT_FIREBASE_PROJECT_ID",
  firebaseStorageBucket: "YOUR_DEVELOPMENT_FIREBASE_STORAGE_BUCKET",
  firebaseMessagingSenderId: "YOUR_DEVELOPMENT_FIREBASE_MESSAGING_SENDER_ID",
  firebaseAppId: "YOUR_DEVELOPMENT_FIREBASE_APP_ID",
  firebaseMeasurementId: "YOUR_DEVELOPMENT_FIREBASE_MEASUREMENT_ID",
  routePrefix: ""
};