export const environment = {
  production: false,
  jwtSecretKey: 'YOUR_PRODUCTION_JWT_SECRET_KEY',
  apiUrl: 'YOUR_PRODUCTION_API_URL',
  firebaseApiKey: "YOUR_PRODUCTION_FIREBASE_API_KEY",
  firebaseAuthDomain: "YOUR_PRODUCTION_FIREBASE_AUTH_DOMAIN",
  firebaseDatabaseURL: "YOUR_PRODUCTION_FIREBASE_DATABASE_URL",
  firebaseProjectId: "YOUR_PRODUCTION_FIREBASE_PROJECT_ID",
  firebaseStorageBucket: "YOUR_PRODUCTION_FIREBASE_STORAGE_BUCKET",
  firebaseMessagingSenderId: "YOUR_PRODUCTION_FIREBASE_MESSAGING_SENDER_ID",
  firebaseAppId: "YOUR_PRODUCTION_FIREBASE_APP_ID",
  firebaseMeasurementId: "YOUR_PRODUCTION_FIREBASE_MEASUREMENT_ID",
  routePrefix: "/YOUR_PROJECT_NAME",
};